defaults:
  - _self_
  - features: default
  - model: logistic
  - preprocessing: one_hot_transformer
  - split: train_test_split
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

input_data_path: "data/raw/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"